# Generated by Django 6.0.5 on 2026-07-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_vacancies', models.IntegerField(default=0, verbose_name='Общее количество активных вакансий в выборке')),
                ('top_skills', models.JSONField(default=list, verbose_name='Топ навыков')),
                ('work_formats', models.JSONField(default=dict, verbose_name='Форматы работы')),
                ('experience_funnel', models.JSONField(default=dict, verbose_name='Опыт работы')),
                ('grades_distribution', models.JSONField(default=dict, verbose_name='Распределение по грейдам')),
                ('vacancies_per_month', models.JSONField(default=list, verbose_name='Динамика вакансий')),
            ],
            options={
                'verbose_name': 'Global Analytics Snapshot',
                'verbose_name_plural': 'Global Analytics Snapshots',
                'db_table': 'analytics_global_snapshot',
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
    ]
