# Generated by Django 6.0.5 on 2026-07-05 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalanalyticssnapshot',
            old_name='vacancies_per_month',
            new_name='vacancies_per_day',
        ),
    ]
