# Generated by Django 6.0.5 on 2026-05-17 21:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Company ID')),
                ('name', models.CharField(help_text='Original name, fetched from vacancy', max_length=255, verbose_name='Company name')),
                ('normalized_name', models.CharField(db_index=True, help_text='Lower case without spaces. Using for search duplicates', max_length=255, unique=True, verbose_name='Normalized name')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'vacancies_company',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('region', models.CharField(blank=True, help_text='For example: CIS(СНГ), Europe, Asia', max_length=100, null=True, verbose_name='Macroregion')),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'vacancies_location',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Skill ID')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'db_table': 'vacancies_skill',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkFormat',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Work Format',
                'verbose_name_plural': 'Work Formats',
                'db_table': 'vacancies_work_format',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Vacancy ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(verbose_name='Description (cleared)')),
                ('salary_min', models.IntegerField(blank=True, null=True, verbose_name='Salary from')),
                ('usd_salary_min', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Salary from (Converted in USD)')),
                ('salary_max', models.IntegerField(blank=True, null=True, verbose_name='Salary up to')),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('status', models.CharField(choices=[('ACT', 'Active'), ('CLS', 'Closed'), ('ARC', 'Archive')], db_index=True, default='ACT', max_length=3)),
                ('grade', models.CharField(blank=True, choices=[('INT', 'Intern'), ('JUN', 'Junior'), ('MID', 'Middle'), ('SEN', 'Senior'), ('LED', 'Lead'), ('DIR', 'Director')], db_index=True, max_length=3, null=True)),
                ('employment_type', models.CharField(blank=True, choices=[('FT', 'Full day'), ('PT', 'Part-time employment'), ('PRJ', 'Project')], db_index=True, max_length=3, null=True)),
                ('english_level', models.CharField(blank=True, choices=[('NS', 'Not specified'), ('A1', 'A1 (Beginner)'), ('A2', 'A2 (Elementary)'), ('B1', 'B1 (Intermediate)'), ('B2', 'B2 (Upper-Intermediate)'), ('C1', 'C1 (Advanced)'), ('C2', 'C2 (Proficient)')], db_index=True, max_length=2, null=True)),
                ('content_hash', models.CharField(max_length=64, unique=True, verbose_name='Hash of the content')),
                ('published_at', models.DateTimeField(db_index=True, verbose_name='Published date')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='vacancies.company')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='vacancies.location')),
                ('skills', models.ManyToManyField(blank=True, related_name='vacancies', to='vacancies.skill')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='sources.source')),
                ('work_formats', models.ManyToManyField(blank=True, related_name='vacancies', to='vacancies.workformat')),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
                'db_table': 'vacancies_vacancy',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='vacancies_v_status_20e66c_idx'), models.Index(fields=['grade', '-published_at'], name='vacancies_v_grade_6c8118_idx'), models.Index(fields=['usd_salary_min', '-published_at'], name='vacancies_v_usd_sal_a999bd_idx')],
            },
        ),
    ]
