# Generated by Django 6.0.5 on 2026-05-18 13:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('sources', '0001_initial'),
        ('vacancies', '0002_alter_vacancy_published_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Contact ID')),
                ('platform', models.CharField(choices=[('TG', 'Telegram'), ('DS', 'Discord'), ('EM', 'Email')], max_length=2)),
                ('details', models.CharField(help_text='For example: @example, example@example.example', max_length=100, verbose_name='Contact link')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'vacancies_contact',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='autor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='contacts_opened_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='sources.source'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='contact',
            field=models.ManyToManyField(related_name='vacancies', to='vacancies.contact'),
        ),
    ]
