# Generated by Django 6.0.5 on 2026-05-19 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_contact_vacancy_autor_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='autor_id',
            new_name='autor',
        ),
    ]
