# Generated by Django 6.0.5 on 2026-05-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_rename_autor_id_vacancy_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='normalized_name',
        ),
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='usd_salary_min',
            field=models.IntegerField(blank=True, db_index=True, help_text='Converted in USD for search by salary min', null=True, verbose_name='Salary from (USD)'),
        ),
    ]
