# Generated by Django 6.0.5 on 2026-05-25 12:25

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_slottransaction_options_and_more"),
        ("sources", "0002_alter_source_platform"),
        ("vacancies", "0005_remove_company_normalized_name_company_slug_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vacancy",
            old_name="autor",
            new_name="author",
        ),
        TrigramExtension(),
        migrations.AddIndex(
            model_name="company",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="company_name_gin", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="skill_name_gin", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="vacancy",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"], name="vacancy_title_gin", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
