# Generated by Django 6.0.5 on 2026-05-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_rename_autor_vacancy_author_company_company_name_gin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='work_formats',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_format',
            field=models.CharField(blank=True, choices=[('RMT', 'Remote'), ('OFF', 'Office'), ('HBR', 'Hybrid')], db_index=True, max_length=3, null=True),
        ),
        migrations.DeleteModel(
            name='WorkFormat',
        ),
    ]
