# Generated by Django 6.0.5 on 2026-05-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_remove_vacancy_work_formats_vacancy_work_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateTimeField(db_index=True, verbose_name='Published date'),
        ),
    ]
