# Generated by Django 6.0.5 on 2026-05-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0008_alter_vacancy_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='experience_from',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Experience from'),
        ),
    ]
