# Generated by Django 6.0.5 on 2026-06-10 08:13

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0010_alter_company_id_alter_contact_id_alter_vacancy_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='Complaint ID')),
                ('reason', models.CharField(choices=[('SCM', 'Scam / Fraud'), ('SAL', 'Fake salary'), ('UNR', 'Employer is unresponsive'), ('OTH', 'Other')], db_index=True, max_length=3, verbose_name='Reason')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Details')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to=settings.AUTH_USER_MODEL, verbose_name='Complainant')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='vacancies.vacancy', verbose_name='Vacancy')),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'db_table': 'vacancies_complaint',
                'ordering': ['-created_at'],
            },
        ),
    ]
