# Generated by Django 6.0.5 on 2026-06-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0011_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='platform',
            field=models.CharField(choices=[('TG', 'Telegram'), ('DS', 'Discord'), ('EM', 'Email'), ('FR', 'Form')], max_length=2),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='english_level',
            field=models.CharField(blank=True, choices=[('A1', 'A1 (Beginner)'), ('A2', 'A2 (Elementary)'), ('B1', 'B1 (Intermediate)'), ('B2', 'B2 (Upper-Intermediate)'), ('C1', 'C1 (Advanced)'), ('C2', 'C2 (Proficient)')], db_index=True, max_length=2, null=True),
        ),
    ]
