# Generated by Django 6.0.5 on 2026-07-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0012_alter_contact_platform_alter_vacancy_english_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='platform',
            field=models.CharField(choices=[('TG', 'Telegram'), ('DS', 'Discord'), ('EM', 'Email'), ('FR', 'Form'), ('NM', 'Number'), ('RD', 'Reddit')], max_length=2),
        ),
    ]
