# Generated by Django 6.0.5 on 2026-07-01 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0013_alter_contact_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Relocation',
                'verbose_name_plural': 'Relocations',
                'db_table': 'vacancies_relocation',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='relocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='vacancies.relocation'),
        ),
    ]
