# Generated by Django 6.0.5 on 2026-07-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0014_relocation_vacancy_relocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relocation',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
