# Generated by Django 6.0.5 on 2026-07-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0015_alter_relocation_country'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('region', 'country', 'city'), name='unique_location'),
        ),
    ]
