# Generated by Django 6.0.5 on 2026-07-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0016_location_unique_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='details',
            field=models.CharField(help_text='For example: @example, example@example.example', max_length=255, verbose_name='Contact link'),
        ),
    ]
