x-airflow-common: &airflow-common
  build:
    context: ./airflow
    dockerfile: Dockerfile
  env_file: .env
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
  depends_on:
    db:
      condition: service_healthy
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
  networks:
    - backend_network

services:
  db:
    image: postgres:17-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PASSWORD:-guest}
    networks:
      - backend_network

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    networks:
      - backend_network

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app
    restart: always
    command: /app/scripts/entrypoint.sh
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    volumes:
      - static:/app/static
      - media:/app/media
    networks:
      - backend_network

  taskiq_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taskiq_worker
    restart: always
    command: taskiq worker apps.core.broker:broker
    env_file: .env
    depends_on:
      - app
      - rabbitmq
    networks:
      - backend_network

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow_webserver
    command: webserver
    ports:
      - "8080:8080"

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    command: scheduler
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock 
      - parser_sessions:/opt/whilework/sessions/app/sessions 

  airflow-init:
    <<: *airflow-common
    container_name: airflow_init
    command: >
      bash -c "airflow db migrate && 
      airflow users create --username admin --password admin --firstname Airflow --lastname Admin --role Admin --email admin@example.com"

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/app/static
      - media:/app/media
    depends_on:
      - app
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data:
  static:
  media:
  parser_sessions: