# Generated by Django 6.0.5 on 2026-05-17 21:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Source ID')),
                ('platform', models.CharField(max_length=50, verbose_name='Platform name')),
                ('name', models.CharField(max_length=255, verbose_name='Source name')),
                ('identifier', models.CharField(help_text='Channel ID, link, or snowflake in Discord (which is what the parser is looking for)', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_parsed_id', models.CharField(blank=True, help_text='ID of the last processed message (for Airflow)', max_length=255, null=True)),
                ('error_count', models.IntegerField(default=0)),
                ('last_error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
                'db_table': 'sources_source',
                'ordering': ['created_at'],
            },
        ),
    ]
