# Generated by Django 6.0.5 on 2026-05-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='platform',
            field=models.CharField(choices=[('DIS', 'Discord'), ('TLG', 'Telegram')], max_length=3, verbose_name='Platform name'),
        ),
    ]
