# Generated by Django 6.0.5 on 2026-05-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_alter_source_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='topic_id',
            field=models.CharField(blank=True, help_text='Auxiliary id for parsing, for example, branch id in TG groups', max_length=255, null=True),
        ),
    ]
