# Generated by Django 6.0.5 on 2026-05-28 14:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_source_topic_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='topic_id',
        ),
        migrations.AlterField(
            model_name='source',
            name='last_parsed_id',
            field=models.CharField(blank=True, help_text='ID of the last processed message (for Parser)', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SourceTopic',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic_id', models.CharField(help_text='Branch ID in Telegram or Discord', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_parsed_id', models.CharField(blank=True, help_text='The ID of the last processed message in this particular topic', max_length=255, null=True)),
                ('error_count', models.IntegerField(default=0)),
                ('last_error_message', models.TextField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='sources.source', verbose_name='Parent Source')),
            ],
            options={
                'verbose_name': 'Source Topic',
                'verbose_name_plural': 'Source Topics',
                'db_table': 'sources_source_topic',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('source', 'topic_id'), name='unique_source_topic')],
            },
        ),
    ]
