# Generated by Django 6.0.5 on 2026-06-02 15:04

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_remove_source_topic_id_alter_source_last_parsed_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='Source ID'),
        ),
        migrations.AlterField(
            model_name='sourcetopic',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
