# Generated by Django 6.0.5 on 2026-06-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_alter_source_id_alter_sourcetopic_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='platform',
            field=models.CharField(choices=[('TLG', 'Telegram')], max_length=3, verbose_name='Platform name'),
        ),
    ]
