# Generated by Django 6.0.5 on 2026-06-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0006_alter_source_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link on source'),
        ),
    ]
