# Generated by Django 6.0.5 on 2026-06-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report404',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Report404',
                'verbose_name_plural': 'Reports404',
                'db_table': 'system_report404',
                'ordering': ['-created_at'],
            },
        ),
    ]
