# Generated by Django 6.0.5 on 2026-06-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('iso', models.CharField(max_length=3, verbose_name='ISO code')),
                ('currency_rate', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'db_table': 'system_currency',
                'ordering': ['-created_at'],
            },
        ),
    ]
