# Generated by Django 6.0.5 on 2026-06-12 10:39

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('FEAT', 'FEAT'), ('FIX', 'FIX'), ('INIT', 'INIT')], max_length=4)),
            ],
            options={
                'verbose_name': 'ProductionLog',
                'verbose_name_plural': 'Production Logs',
                'db_table': 'community_production_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Suggest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='Suggest ID')),
                ('status', models.CharField(blank=True, choices=[('NEW', 'New'), ('PLN', 'Planned'), ('RVW', 'Review'), ('MDR', 'Moderation'), ('ARC', 'Archive')], db_index=True, default='MDR', max_length=3)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suggest',
                'verbose_name_plural': 'Suggests',
                'db_table': 'community_suggest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
