# Generated by Django 6.0.5 on 2026-06-15 08:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_productionlog_suggest_delete_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='suggest',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_suggests', to=settings.AUTH_USER_MODEL),
        ),
    ]
