# Generated by Django 6.0.5 on 2026-05-18 13:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vacancies', '0002_alter_vacancy_published_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='User ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('available_slots', models.IntegerField(default=0, help_text='The number of available slots for job placement')),
                ('company_blacklist', models.ManyToManyField(blank=True, related_name='users', to='vacancies.company')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'accounts_user',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SlotTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Transaction ID')),
                ('slots_added', models.IntegerField(help_text='Number of slots purchased')),
                ('payment_status', models.CharField(choices=[('SCS', 'Seccessfully'), ('EXP', 'Expectation'), ('CNC', 'Cancel')], max_length=3)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_transactions', to='accounts.user')),
            ],
            options={
                'verbose_name': 'SlotTransaction',
                'verbose_name_plural': 'SlotTransactions',
                'db_table': 'accounts_slot_transaction',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('d', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Notification ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'accounts_notification',
                'ordering': ['created_at'],
            },
        ),
    ]
