# Generated by Django 6.0.5 on 2026-05-19 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slottransaction',
            options={'ordering': ['created_at'], 'verbose_name': 'Slot Transaction', 'verbose_name_plural': 'Slot Transactions'},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='slottransaction',
            old_name='user_id',
            new_name='user',
        ),
    ]
