# Generated by Django 6.0.5 on 2026-05-21 21:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_slottransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slottransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Slot Transaction', 'verbose_name_plural': 'Slot Transactions'},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='d',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AlterField(
            model_name='slottransaction',
            name='payment_status',
            field=models.CharField(choices=[('SCS', 'Success'), ('PND', 'Pending'), ('CNC', 'Cancelled')], default='PND', max_length=3),
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='User Notification ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to='accounts.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to='accounts.user')),
            ],
            options={
                'verbose_name': 'User Notification',
                'verbose_name_plural': 'User Notifications',
                'db_table': 'accounts_user_notification',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='users',
            field=models.ManyToManyField(related_name='notifications', through='accounts.UserNotification', to='accounts.user'),
        ),
        migrations.AddConstraint(
            model_name='usernotification',
            constraint=models.UniqueConstraint(fields=('user', 'notification'), name='unique_user_notification'),
        ),
    ]
