# Generated by Django 6.0.5 on 2026-06-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_groups_user_is_active_user_is_staff_and_more'),
        ('vacancies', '0011_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='viewed_vacancies',
            field=models.ManyToManyField(blank=True, related_name='users', to='vacancies.vacancy'),
        ),
    ]
