upstream django_app {
    server app:8000;
}

server {
    listen 80;

    location /static/ {
        alias /app/static/;
    }
    
    location /media/ {
        alias /app/media/;
    }

    location /api/internal/ {
        deny all;

        proxy_pass http://django_app;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr; 
        proxy_redirect off;
    }

    location / {
        proxy_pass http://django_app;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }
}