# Generated by Django 6.0.5 on 2026-05-19 11:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserRawMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Raw Vacancy ID')),
                ('external_msg_id', models.CharField(help_text='The ID of the message in the source', max_length=255, verbose_name='External Message ID')),
                ('raw_text', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PND', 'Pending'), ('PRC', 'Processed'), ('FLD', 'Failed')], default='PND', max_length=3)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_raw_messages', to='sources.source', verbose_name='Source ID')),
            ],
            options={
                'verbose_name': 'Parsed Raw Message',
                'verbose_name_plural': 'Parsed Raw Messages',
                'db_table': 'vacancies_parsed_raw_message',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_msg_id'), name='unique_source_message')],
            },
        ),
    ]
