# Generated by Django 6.0.5 on 2026-05-21 21:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parserrawmessage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Raw Message ID'),
        ),
        migrations.AlterModelTable(
            name='parserrawmessage',
            table='inbox_parsed_raw_message',
        ),
    ]
