# Generated by Django 6.0.5 on 2026-05-28 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_alter_parserrawmessage_id_and_more'),
        ('sources', '0004_remove_source_topic_id_alter_source_last_parsed_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parserrawmessage',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_messages', to='sources.sourcetopic'),
        ),
    ]
