# Generated by Django 6.0.5 on 2026-06-02 15:04

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_parserrawmessage_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parserrawmessage',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='Raw Message ID'),
        ),
    ]
