# Generated by Django 6.0.5 on 2026-06-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0004_alter_parserrawmessage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parserrawmessage',
            name='status',
            field=models.CharField(choices=[('PND', 'Pending'), ('PRC', 'Processed'), ('FLD', 'Failed'), ('REJ', 'Rejected (Not a vacancy)')], default='PND', max_length=3),
        ),
    ]
