# Generated by Django 6.0.5 on 2026-06-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0005_alter_parserrawmessage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parserrawmessage',
            name='status',
            field=models.CharField(choices=[('PND', 'Pending'), ('PRC', 'Processed'), ('PRCG', 'Processing'), ('FLD', 'Failed'), ('REJ', 'Rejected (Not a vacancy)')], default='PND', max_length=4),
        ),
    ]
