# Generated by Django 6.0.5 on 2026-06-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(default='Anonym', max_length=125),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
