name: Django CI

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" > .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=test_db" >> .env

      - name: Build and Run Tests in Docker
        run: |
          docker compose up -d --build app
          docker compose exec -T app pytest
          docker compose down -v
      
      - name: Cleanup
        if: always()
        run: |
          rm -f .env
          docker image prune -f